\copy student FROM 'data/students.csv' DELIMITER ',' CSV;
\copy class FROM 'data/class.csv' DELIMITER ',' CSV;
\copy job FROM 'data/jobs.csv' DELIMITER ',' CSV;
\copy employedby FROM 'data/employedBy.csv' DELIMITER ',' CSV;
\copy hobby FROM 'data/hobby.csv' DELIMITER ',' CSV;
\copy participates FROM 'data/participates.csv' DELIMITER ',' CSV;
\copy subject FROM 'data/subject.csv' DELIMITER ',' CSV;
\copy studies FROM 'data/studies.csv' DELIMITER ',' CSV;
\copy takes FROM 'data/takes.csv' DELIMITER ',' CSV;
